services:
  ionsfu:
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    container_name: ion-sfu-jsonrpc
    ports:
      - "7000:7000"
      - "5000-5200:5000-5200/udp"
    volumes:
      - ./conf/sfu.toml:/configs/sfu.toml:ro
    networks:
      - my_network
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DOMAIN=${DOMAIN}
      - SSL_KEY_PATH=/etc/ssl/server.key
      - SSL_CERT_PATH=/etc/ssl/server.crt
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FILE_STORAGE_PATH=/files
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ${SSL_KEY_PATH}:/etc/ssl/server.key:ro
      - ${SSL_CRT_PATH}:/etc/ssl/server.crt:ro
      - files:/files
    depends_on:
      - mongodb
      - ionsfu
    networks:
      - my_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - my_network
    
  nginx:
    image: nginx:1.27.4-alpine
    container_name: nginx
    user: "root"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ../web/dist:/usr/share/nginx/html:ro
      - ${SSL_KEY_PATH}:/etc/ssl/server.key:ro
      - ${SSL_CRT_PATH}:/etc/ssl/server.crt:ro
    command: /bin/sh -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - server
    networks:
      - my_network

volumes:
  mongo_data:
  mongo_config:
  files:

networks:
  my_network:
    driver: bridge